run:
  timeout: 5m
  tests: false

issues.skip-files:
    - 'internal/config/http_config.go'
    - 'internal/config/config.go'

linters:
   enable-all: true
   disable:
     - exportloopref
     - godot
     - cyclop
     - depguard
     - dupl
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - err113
     - gofumpt
     - mnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
